#!/bin/bash

echo "Installing input methods ..."

pkgs="adobe-source-han-sans-cn-fonts adobe-source-han-serif-cn-fonts"

echo $pkgs

yay -S $pkgs --noconfirm

touch ~/.xprofile
echo "export GTK_IM_MODULE=ibus" >> ~/.xprofile
echo "export QT_IM_MODULE=ibus" >> ~/.xprofile
echo "export XMODIFIERS=@im=ibus" >> ~/.xprofile

echo "Installation finished!"
